services:
  - type: web
    name: todoapp-frontend
    env: static
    buildCommand: npm install --production=false && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: REACT_APP_API_URL
        value: https://todo-app-rqn6.onrender.com/api
      - key: GENERATE_SOURCEMAP
        value: false
